name: "Reviewer lottery"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
    paths: 
      - _projects/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: uesteibar/reviewer-lottery@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}